# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20170415_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet')),
            ],
        ),
    ]
