# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20170424_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retweetship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='twitter.Tweet')),
                ('re_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re', to='twitter.Tweet')),
            ],
            options={
                'ordering': ['-re_date'],
            },
        ),
    ]
