# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_retweetship'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet_num',
            field=models.IntegerField(default=0),
        ),
    ]
