# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_retweet',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_num',
        ),
        migrations.AddField(
            model_name='tweet',
            name='original_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet'),
        ),
    ]
