# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_auto_20170426_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply_num',
            field=models.IntegerField(default=0),
        ),
    ]
