# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_tweet_reply_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='reply_num',
        ),
    ]
