# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0013_remove_tweet_reply_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
