# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0014_tweet_like_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replyship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_tweet', to='twitter.Tweet')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_replied_tweet', to='twitter.Tweet')),
                ('tweet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_replied_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reply_date'],
            },
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='tweet',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
