# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0016_tweet_reply_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificate_date', models.IntegerField(default=django.utils.timezone.now)),
                ('initiative_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificate_user', to=settings.AUTH_USER_MODEL)),
                ('notificated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificated_user', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet')),
            ],
            options={
                'ordering': ['-notificate_date'],
            },
        ),
    ]
