# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0018_auto_20170430_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='nofiticate_type',
            field=models.CharField(choices=[('L', 'like'), ('T', 'tweet'), ('R', 'retweet'), ('F', 'Follow')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet'),
        ),
    ]
