# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0021_stream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-notify_date']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notificate_date',
            new_name='notify_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='initiative_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificate_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificated_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notified_type',
            field=models.CharField(blank=True, choices=[('M', 'mention'), ('Y', 'reply'), ('R', 'retweet'), ('RM', 'retweet_mention'), ('L', 'like'), ('LM', 'like_mention'), ('F', 'follow')], default='Y', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
